fix: cron

diff --git a/config/my_cron_file b/config/my_cron_file
--- a/config/my_cron_file
+++ b/config/my_cron_file
@@ -4,19 +4,5 @@ WORDPRESS_DB_HOST=mysql:3306
 WORDPRESS_DB_USER=root
 WORDPRESS_DB_PASSWORD=wordpress
 WORDPRESS_DB_NAME=realty
-08 19 * * 6 bash -c '(
-    echo "Execution started at $(date)" >> /var/log/cron.log
-    /usr/local/bin/php /var/www/html/get_json.php >> /var/log/cron.log 2>&1
-    if [ $? -ne 0 ]; then
-        echo "Error occurred at $(date)" >> /var/log/cron.log
-        for i in {1..20}; do
-            /usr/local/bin/php /var/www/html/critical_error_message_telegram.php >> /var/log/cron.log 2>&1
-            if [ $? -eq 0 ]; then
-                break
-            else
-                echo "Retry $i failed at $(date)" >> /var/log/cron.log
-            fi
-        done
-    fi
-)'
+59 09 * * 1 (echo "Execution started at $(date)" && /usr/local/bin/php /var/www/html/get_json.php >> /var/log/cron.log 2>&1) || (echo "Error occurred at $(date)" >> /var/log/cron.log && /usr/local/bin/php /var/www/html/critical_error_message_telegram.php >> /var/log/cron.log 2>&1)
 
